calendar:
  holidays:
    - "2026-01-01"
    - "2026-01-02"
    - "2026-01-03"
    - "2026-01-04"
    - "2026-01-05"
    - "2026-01-06"
    - "2026-01-07"
    - "2026-01-08"
    - "2026-02-23"
    - "2026-03-08"
    - "2024-05-01"
    - "2024-05-09"
    - "2024-06-12"
    - "2024-11-04"
  average-days-in-month: 29.3

  # При добавлении параметра weekends вида:
  # weekends:
  #    - 2026-01-10
  #    - 2026-01-11
  #    - 2026-01-15
  # Эти даты будут исключены из расчёта
